//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/chrishanna/Documents/Github/dby/DarkBasicYo/DarkBasicYo/AntlrStuff/DarkBasicYo.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace DarkBasicYoAntlr {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="DarkBasicYoParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface IDarkBasicYoVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="DarkBasicYoParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] DarkBasicYoParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DarkBasicYoParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] DarkBasicYoParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DarkBasicYoParser.printStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrintStatement([NotNull] DarkBasicYoParser.PrintStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DarkBasicYoParser.waitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWaitStatement([NotNull] DarkBasicYoParser.WaitStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DarkBasicYoParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignmentStatement([NotNull] DarkBasicYoParser.AssignmentStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DarkBasicYoParser.loopStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoopStatement([NotNull] DarkBasicYoParser.LoopStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DarkBasicYoParser.conditionalStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConditionalStatement([NotNull] DarkBasicYoParser.ConditionalStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DarkBasicYoParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] DarkBasicYoParser.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DarkBasicYoParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelationalOperator([NotNull] DarkBasicYoParser.RelationalOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DarkBasicYoParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] DarkBasicYoParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="DarkBasicYoParser.arithmeticOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArithmeticOperator([NotNull] DarkBasicYoParser.ArithmeticOperatorContext context);
}
} // namespace DarkBasicYoAntlr
