//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/chrishanna/Documents/Github/dby/DarkBasicYo/DarkBasicYo/AntlrStuff/DarkBasicYo.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace DarkBasicYoAntlr {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="DarkBasicYoParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface IDarkBasicYoListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="DarkBasicYoParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] DarkBasicYoParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DarkBasicYoParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] DarkBasicYoParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DarkBasicYoParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] DarkBasicYoParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DarkBasicYoParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] DarkBasicYoParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DarkBasicYoParser.printStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintStatement([NotNull] DarkBasicYoParser.PrintStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DarkBasicYoParser.printStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintStatement([NotNull] DarkBasicYoParser.PrintStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DarkBasicYoParser.waitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWaitStatement([NotNull] DarkBasicYoParser.WaitStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DarkBasicYoParser.waitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWaitStatement([NotNull] DarkBasicYoParser.WaitStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DarkBasicYoParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentStatement([NotNull] DarkBasicYoParser.AssignmentStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DarkBasicYoParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentStatement([NotNull] DarkBasicYoParser.AssignmentStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DarkBasicYoParser.loopStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopStatement([NotNull] DarkBasicYoParser.LoopStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DarkBasicYoParser.loopStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopStatement([NotNull] DarkBasicYoParser.LoopStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DarkBasicYoParser.conditionalStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionalStatement([NotNull] DarkBasicYoParser.ConditionalStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DarkBasicYoParser.conditionalStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionalStatement([NotNull] DarkBasicYoParser.ConditionalStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DarkBasicYoParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] DarkBasicYoParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DarkBasicYoParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] DarkBasicYoParser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DarkBasicYoParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalOperator([NotNull] DarkBasicYoParser.RelationalOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DarkBasicYoParser.relationalOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalOperator([NotNull] DarkBasicYoParser.RelationalOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DarkBasicYoParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] DarkBasicYoParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DarkBasicYoParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] DarkBasicYoParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="DarkBasicYoParser.arithmeticOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmeticOperator([NotNull] DarkBasicYoParser.ArithmeticOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="DarkBasicYoParser.arithmeticOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmeticOperator([NotNull] DarkBasicYoParser.ArithmeticOperatorContext context);
}
} // namespace DarkBasicYoAntlr
