// This is a generated file. Do not edit directly.

using System;
using FadeBasic;
using FadeBasic.Launch;
using FadeBasic.Virtual;

public class Generated_toast3 : ILaunchable
{
    // this byteCode represents a fully compiled program
    public byte[] Bytecode => _byteCode;

    // this table represents the baked commands available within the program
    public CommandCollection CommandCollection => _collection;

    #region method table
    private static readonly CommandCollection _collection = new CommandCollection(
        new FadeBasic.FadeBasicCommands()
    );
    #endregion

    #region bytecode
    protected byte[] _byteCode = LaunchUtil.Unpack64(encodedByteCode);
    protected const string encodedByteCode = "AQADAAAACQAsAAEAZAAAAAkABwErACwDAQABAAAALAQBAAEAAAArAwMBAAQAAAADCiwCAQAAAAAACQAHBQEAAAAAACsAAQABAAAAAQD/////AwImCAUbAQClAAAAJQgFGgEAbwAAACMBAKUAAAAVCAEBAAIAAAAOCQAPAQAEAAAAKwQIBQMBAAQAAAADKwICDAgFAQABAAAAAgkABwUBAD0AAAAVEgB1AAAAEgBuAAAAEgBzAAAAEgBvAAAAEgByAAAAEgB0AAAAEgBlAAAAEgBkAAAAAQAgAAAAEQoTCQkBAAAAAAAOAQBqAwAAFgEAAAAAACsAAQABAAAAAQD/////AwIBAAIDAAAWEgBzAAAAEgBvAAAAEgByAAAAEgB0AAAAEgBlAAAAEgBkAAAAAQAYAAAAEQoTCQkBAAAAAAAOAQBqAwAAFgEA////fxUqKAkACQAHBgkACQAHBwEABAAAACsECAYDAQAEAAAAAysCAgsNAAkABwgIBwEAAQAAAAEA/////wMCCQAHCQgHCQAHCggHCAYBAAEAAAABAP////8DAiYIChsBAH4CAAAlCAoaAQDBAQAAIwEAfgIAABUBAAQAAAArBAgKAwEABAAAAAMrAgILDQAICBkJAAEA7AEAACMBAGgCAAAVCAkBAAEAAAACCQAHCQEABAAAACsECAkDAQAEAAAAAysCAgsNAAkABwsBAAQAAAArBAgKAwEABAAAAAMrAgILDQAJAA8BAAQAAAArBAgJAwEABAAAAAMrAgIMCAsJAA8BAAQAAAArBAgKAwEABAAAAAMrAgIMAQBpAgAAFRQUCAoBAAEAAAACCQAHCgEAkwEAABUBAAQAAAArBAgJAQABAAAAAgMBAAQAAAADKwICCw0ACQAHCwEABAAAACsECAYDAQAEAAAAAysCAgsNAAkADwEABAAAACsECAkBAAEAAAACAwEABAAAAAMrAgIMCAsJAA8BAAQAAAArBAgGAwEABAAAAAMrAgIMCAkBAAEAAAACKRcpFyooCQAJAAcMCQAJAAcNCA0IDBkJAAEAJAMAACMBAGUDAAAVCA0IDAEAUAEAABYJAAcOCA0IDgEAAQAAAAEA/////wMCAQACAwAAFggOAQABAAAAAggMAQACAwAAFgEAZgMAABUUFCkXKigBAAAAAAAJAAcFAQAAAAAAKwABAAEAAAABAP////8DAiYIBRsBANoDAAAlCAUaAQCnAwAAIwEA2gMAABUBAAQAAAArBAgFAwEABAAAAAMrAgILDQABAAAAAAAOCAUBAAEAAAACCQAHBQEAdQMAABUpFw==";
    #endregion
}
