

using System.Collections.Generic;
using DarkBasicYo.Virtual;

namespace DarkBasicYo
{
    public class StandardCommands
    {
        public static CommandCollection LimitedCommands => new CommandCollection(new DarkBasicCommands());
    }

    public class SubVm : VirtualMachine
    {
        public SubVm(IEnumerable<byte> program) : base(program)
        {
        }

        public SubVm(byte[] program) : base(program)
        {
        }
    }
    
    public class Example
    {
        
        
        public static void Test()
        {
            var commands = new DarkBasicCommands();
            
            commands.Commands[0].executor(null);
            // commands.Count
            // GeneratedDarkBasicCommands.Call2_Ana(null);
            // DarkBasicCommandUtil.Autogenerated.GeneratedDarkBasicCommands.Call2_Ana(null);

        }
        
    }
}