
// using TunaTest;
// using TunaTest;

// using TunaTester;

namespace DarkBasicYo
{
    public class GenTest
    {
        public static void X()
        {
            // var x = new DarkBasicCommandUtil.Autogenerated.DarkBasicCommands();
            
            // TunaTest
            // TunaTester2.
            // TunaTester4
            // var x = TunaTester5.x;
            // var x = TunaTester5.z;
            // DarkbasicCommandU
            // TunaTester.TunaTest.
        }
    }
}