using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;
using FadeBasic.Launch;
using Microsoft.VisualStudio.TestPlatform.ObjectModel.Logging;

namespace FadeBasic.TestAdapter
{
    /// <summary>
    /// Reflection-based loader that turns a built test assembly path into an
    /// <see cref="ITestLaunchable"/> instance. Shared between the discoverer
    /// (which walks the manifest to emit <c>TestCase</c>s) and the executor
    /// (which re-loads the launchable to dispatch a run).
    /// </summary>
    /// <remarks>
    /// The launchable is a class generated by <c>LaunchableGenerator</c> with
    /// a parameterless constructor. The convention this loader enforces is:
    /// "exactly one non-abstract <see cref="ITestLaunchable"/> with a
    /// parameterless ctor per assembly." Zero (a non-Fade C# project) is
    /// silent; more than one is a build-time bug we surface as a logger
    /// error rather than failing the whole IDE discovery pass.
    ///
    /// <para>
    /// Each load goes into its own collectible <see cref="AssemblyLoadContext"/>
    /// so a rebuild of the consumer's test DLL can be picked up without
    /// restarting <c>vstest.console</c>. We track the assembly's last-write
    /// timestamp on cache; when a TryLoad observes a fresher mtime, the old
    /// context is unloaded and the assembly is reloaded fresh. This is what
    /// makes "edit a .fbasic, hit Run in the Test Explorer" work without a
    /// full solution rebuild — the IDE's incremental build of the test
    /// project regenerates <c>GeneratedFade.g.cs</c>, MSBuild rebuilds the
    /// DLL, and the next discovery/execution call observes the new mtime
    /// and reloads.
    /// </para>
    ///
    /// <para>
    /// The custom <see cref="AssemblyLoadContext"/> overrides
    /// <see cref="AssemblyLoadContext.Load"/> to return <c>null</c> for
    /// every dependency, which delegates resolution to the default ALC.
    /// That keeps <see cref="ITestLaunchable"/> as the SAME runtime type
    /// across the adapter and the freshly-loaded consumer assembly — without
    /// it, the <c>typeof(ITestLaunchable).IsAssignableFrom(t)</c> check
    /// would fail because the interface would be a distinct type per ALC.
    /// </para>
    /// </remarks>
    internal static class FadeTestLaunchableLoader
    {
        // Per-path cache. Stores the last-loaded launchable, the assembly
        // mtime at the time of load, and the collectible ALC we own (so we
        // can unload it when the file changes). A null launchable means
        // "we inspected this DLL, it's not a Fade project" — preserved as
        // a negative cache to avoid re-scanning every keystroke.
        private static readonly Dictionary<string, CachedEntry> _cache =
            new(StringComparer.OrdinalIgnoreCase);

        // Test-only direct overrides, checked before the file-backed cache.
        // Bypasses ALC + mtime entirely so tests can drive the executor with
        // an in-memory launchable.
        private static readonly Dictionary<string, ITestLaunchable> _testOverrides =
            new(StringComparer.OrdinalIgnoreCase);

        private static readonly object _lock = new object();

        public static bool TryLoad(
            string source,
            IMessageLogger? logger,
            out ITestLaunchable launchable)
        {
            launchable = null!;

            string fullPath;
            try
            {
                fullPath = Path.GetFullPath(source);
            }
            catch
            {
                return false;
            }

            // Test override path first — never touches the filesystem cache.
            lock (_lock)
            {
                if (_testOverrides.TryGetValue(fullPath, out var stub))
                {
                    launchable = stub;
                    return true;
                }
            }

            long currentMtime = TryGetMtime(fullPath);

            // Cache hit when fresh; invalidate (and unload) on stale mtime.
            lock (_lock)
            {
                if (_cache.TryGetValue(fullPath, out var cached))
                {
                    if (cached.AssemblyMtimeTicks == currentMtime)
                    {
                        if (cached.Launchable == null) return false;
                        launchable = cached.Launchable;
                        return true;
                    }
                    // Stale — unload the old ALC so the GC can collect it,
                    // and drop the cache entry so we reload below.
                    UnloadQuietly(cached.Context);
                    _cache.Remove(fullPath);
                }
            }

            FadeLaunchableLoadContext? newCtx = null;
            ITestLaunchable? instance = null;
            try
            {
                newCtx = new FadeLaunchableLoadContext(
                    "FadeLaunchable:" + Path.GetFileNameWithoutExtension(fullPath));
                instance = LoadCore(fullPath, logger, newCtx);
            }
            catch (Exception ex)
            {
                logger?.SendMessage(TestMessageLevel.Warning,
                    $"FadeBasic.TestAdapter: failed to inspect {Path.GetFileName(fullPath)}: {ex.Message}");
                UnloadQuietly(newCtx);
                lock (_lock)
                {
                    // Cache the failure with the current mtime — same DLL won't
                    // be re-inspected until it's modified.
                    _cache[fullPath] = new CachedEntry(launchable: null, currentMtime, context: null);
                }
                return false;
            }

            if (instance == null)
            {
                // Not a Fade project, or had >1 launchable type (already logged).
                UnloadQuietly(newCtx);
                lock (_lock)
                {
                    _cache[fullPath] = new CachedEntry(launchable: null, currentMtime, context: null);
                }
                return false;
            }

            lock (_lock)
            {
                _cache[fullPath] = new CachedEntry(instance, currentMtime, newCtx);
            }

            launchable = instance;
            return true;
        }

        private static ITestLaunchable? LoadCore(
            string fullPath,
            IMessageLogger? logger,
            FadeLaunchableLoadContext ctx)
        {
            // LoadFromAssemblyPath inside our context loads the consumer's DLL
            // into THIS ALC. Its dependencies (FadeBasic.dll → ITestLaunchable)
            // are resolved via Load() returning null, which falls back to the
            // default ALC where our own copy already lives — keeping type
            // identity intact.
            var asm = ctx.LoadFromAssemblyPath(fullPath);

            Type[] types;
            try
            {
                types = asm.GetTypes();
            }
            catch (ReflectionTypeLoadException ex)
            {
                // Some types in the assembly couldn't load. Tolerable as long
                // as our launchable type itself is intact.
                types = ex.Types.Where(t => t != null).ToArray()!;
            }

            var candidates = types
                .Where(t => t != null
                            && !t.IsAbstract
                            && !t.IsInterface
                            && typeof(ITestLaunchable).IsAssignableFrom(t)
                            && t.GetConstructor(Type.EmptyTypes) != null)
                .ToList();

            if (candidates.Count == 0) return null;

            if (candidates.Count > 1)
            {
                var names = string.Join(", ", candidates.Select(c => c.FullName));
                logger?.SendMessage(TestMessageLevel.Error,
                    $"FadeBasic.TestAdapter: {Path.GetFileName(fullPath)} contains {candidates.Count} ITestLaunchable types ({names}); expected exactly one.");
                return null;
            }

            return (ITestLaunchable?)Activator.CreateInstance(candidates[0]);
        }

        private static long TryGetMtime(string fullPath)
        {
            try
            {
                return File.GetLastWriteTimeUtc(fullPath).Ticks;
            }
            catch
            {
                // File missing or inaccessible — return 0 so any later valid
                // mtime invalidates the cache entry naturally.
                return 0;
            }
        }

        private static void UnloadQuietly(AssemblyLoadContext? ctx)
        {
            if (ctx == null) return;
            try { ctx.Unload(); }
            catch { /* best-effort; the GC may collect later */ }
        }

        /// <summary>
        /// Test-only cache reset. The IDE process holds adapters across runs,
        /// so caching is correct in production; tests that swap assembly
        /// contents need to invalidate.
        /// </summary>
        internal static void ResetCacheForTests()
        {
            lock (_lock)
            {
                foreach (var entry in _cache.Values)
                {
                    UnloadQuietly(entry.Context);
                }
                _cache.Clear();
                _testOverrides.Clear();
            }
        }

        /// <summary>
        /// Test-only seam — pre-register an in-memory launchable for a path
        /// so the executor's <c>RunGroup</c> can be exercised without
        /// writing a real .dll to disk. Returns an <see cref="System.IDisposable"/>
        /// that clears the entry on dispose.
        /// </summary>
        internal static System.IDisposable RegisterForTests(string assemblyPath, ITestLaunchable launchable)
        {
            var fullPath = Path.GetFullPath(assemblyPath);
            lock (_lock)
            {
                _testOverrides[fullPath] = launchable;
            }
            return new RegistrationScope(fullPath);
        }

        private sealed class CachedEntry
        {
            public ITestLaunchable? Launchable { get; }
            public long AssemblyMtimeTicks { get; }
            public AssemblyLoadContext? Context { get; }

            public CachedEntry(ITestLaunchable? launchable, long ticks, AssemblyLoadContext? context)
            {
                Launchable = launchable;
                AssemblyMtimeTicks = ticks;
                Context = context;
            }
        }

        private sealed class FadeLaunchableLoadContext : AssemblyLoadContext
        {
            public FadeLaunchableLoadContext(string name) : base(name, isCollectible: true) { }

            // Returning null delegates dependency resolution to the default
            // ALC. We only ever call LoadFromAssemblyPath on the consumer's
            // own DLL; everything it references resolves elsewhere — most
            // importantly, FadeBasic.dll which carries ITestLaunchable.
            protected override Assembly? Load(AssemblyName assemblyName) => null;
        }

        private sealed class RegistrationScope : System.IDisposable
        {
            private readonly string _path;
            public RegistrationScope(string path) { _path = path; }
            public void Dispose()
            {
                lock (_lock) _testOverrides.Remove(_path);
            }
        }
    }
}
