name: Release

on:
  workflow_dispatch:
    inputs:
      commit:
        type: string
        description: Commit hash to deploy
        default: main
      majorSemver:
        type: number
        description: major number in semver 
        required: true
        default: 0
      minorSemver:
        type: number
        description: minor number in semver 
        required: true
        default: 0
      patchSemver:
        type: number
        description: patch number in semver 
        required: true
        default: 0
      publishVsCode:
        type: boolean
        description: publish the vs code extension?
        required: true
        default: true
      publishNuget:
        type: boolean
        description: publish the nuget packages extension?
        required: true
        default: true

run-name:  Release ${{ inputs.majorSemver }}.${{ inputs.minorSemver }}.${{ inputs.patchSemver }} by @${{ github.actor }}
jobs:
  release:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    concurrency:
      group: release
      cancel-in-progress: true
    steps:
    
      - uses: actions/checkout@v4
        with: 
          ref: ${{ github.event.inputs.commit }}

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'


      - name: pre-test build 
        working-directory: ./FadeBasic
        run: |
          sh ./setup.sh
          sh ./install.sh 0.0.1000 1
      - name: run tests
        working-directory: ./FadeBasic
        run: dotnet test Tests
        env: 
          FadeNugetVersion: '0.0.1000.1'

      - name: set FADE_NUGET_DRYRUN based on input
        if: inputs.publishNuget == false
        run: echo "FADE_NUGET_DRYRUN=true" >> $GITHUB_ENV

      - name: Run Build Script
        working-directory: ./FadeBasic
        run: sh ./install.sh ${{ inputs.majorSemver }}.${{ inputs.minorSemver }}.${{ inputs.patchSemver }} 1 ${{ secrets.NUGET_HOST }} ${{ secrets.NUGET_API_KEY }}
        # env:
        #   FADE_NUGET_DRYRUN: true

      - name: Run VsCode Scripts
        working-directory: ./VsCode/basicscript
        if: inputs.publishVsCode == true
        run: |
          sudo chmod -R 777 out
          npm install
          npm version ${{ inputs.majorSemver }}.${{ inputs.minorSemver }}.${{ inputs.patchSemver }}
          npx vsce publish -p ${{ secrets.VS_CODE_AZURE_PAT }}

